<!-- Title for handling missing data methods, including fillna, interpolate, and dropna. -->
## <font color="maroon"><h4 align="center">Handling Missing Data - fillna, interpolate, dropna</font>

In [1]:
# Load pandas, read weather_data.csv with parsed dates, inspect the first row type and display the DataFrame.
import pandas as pd
df = pd.read_csv("weather_data.csv",parse_dates=['day'])
type(df.day[0])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [2]:
# Set the DataFrame index to the day column and display the updated DataFrame.
df.set_index('day',inplace=True)
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<!-- Section header for fillna examples. -->
## <font color="blue">fillna</font>

<!-- Describe filling all missing values with a single constant. -->
<font color="purple">**Fill all NaN with one specific value**</font>

In [3]:
# Replace all missing values with 0 and display the resulting DataFrame.
new_df = df.fillna(0)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          0.0        9.0   Sunny
2017-01-05         28.0        0.0    Snow
2017-01-06          0.0        7.0       0
2017-01-07         32.0        0.0    Rain
2017-01-08          0.0        0.0   Sunny
2017-01-09          0.0        0.0       0
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<!-- Describe filling NaNs with different values for each column. -->
<font color="purple">**Fill na using column names and dict**</font>

In [4]:
# Fill missing values using a dictionary of column-specific replacements and display the result.
new_df = df.fillna({
        'temperature': 0,
        'windspeed': 0,
        'event': 'No Event'
    })
new_df

            temperature  windspeed     event
day
2017-01-01         32.0        6.0      Rain
2017-01-04          0.0        9.0     Sunny
2017-01-05         28.0        0.0      Snow
2017-01-06          0.0        7.0  No Event
2017-01-07         32.0        0.0      Rain
2017-01-08          0.0        0.0     Sunny
2017-01-09          0.0        0.0  No Event
2017-01-10         34.0        8.0    Cloudy
2017-01-11         40.0       12.0     Sunny

<!-- Describe using method-based fill operations for missing values. -->
<font color="purple">**Use method to determine how to fill na values**</font>

In [5]:
# Forward-fill missing values along the index and display the result.
new_df = df.ffill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        7.0   Sunny
2017-01-09         32.0        7.0   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [6]:
# Backward-fill missing values along the index and display the result.
new_df = df.bfill()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         28.0        9.0   Sunny
2017-01-05         28.0        7.0    Snow
2017-01-06         32.0        7.0    Rain
2017-01-07         32.0        8.0    Rain
2017-01-08         34.0        8.0   Sunny
2017-01-09         34.0        8.0  Cloudy
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<!-- Describe filling missing values across columns instead of rows. -->
<font color="purple">**Use of axis**</font>

In [7]:
# Backward-fill missing values across columns and display the result.
new_df = df.bfill(axis="columns") # axis is either "index" or "columns"
new_df

           temperature windspeed   event
day
2017-01-01        32.0       6.0    Rain
2017-01-04         9.0       9.0   Sunny
2017-01-05        28.0      Snow    Snow
2017-01-06         7.0       7.0     NaN
2017-01-07        32.0      Rain    Rain
2017-01-08       Sunny     Sunny   Sunny
2017-01-09         NaN       NaN     NaN
2017-01-10        34.0       8.0  Cloudy
2017-01-11        40.0      12.0   Sunny

<!-- Explain the limit parameter for fill operations. -->
<font color="purple">**limit parameter**</font>

In [8]:
# Forward-fill missing values with a maximum of one consecutive fill and display the result.
new_df = df.ffill(limit=1)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04         32.0        9.0   Sunny
2017-01-05         28.0        9.0    Snow
2017-01-06         28.0        7.0    Snow
2017-01-07         32.0        7.0    Rain
2017-01-08         32.0        NaN   Sunny
2017-01-09          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<!-- Section header for interpolation examples. -->
### <font color="blue">interpolate</font>

In [9]:
# Interpolate only the numeric temperature and windspeed columns and display the result.
new_df = df[["temperature","windspeed"]].interpolate()
new_df

            temperature  windspeed
day
2017-01-01    32.000000       6.00
2017-01-04    30.000000       9.00
2017-01-05    28.000000       8.00
2017-01-06    30.000000       7.00
2017-01-07    32.000000       7.25
2017-01-08    32.666667       7.50
2017-01-09    33.333333       7.75
2017-01-10    34.000000       8.00
2017-01-11    40.000000      12.00

In [10]:
# Perform time-based interpolation on the numeric temperature and windspeed columns and display the result.
new_df = df[["temperature","windspeed"]].interpolate(method="time")
new_df

            temperature  windspeed
day
2017-01-01    32.000000       6.00
2017-01-04    29.000000       9.00
2017-01-05    28.000000       8.00
2017-01-06    30.000000       7.00
2017-01-07    32.000000       7.25
2017-01-08    32.666667       7.50
2017-01-09    33.333333       7.75
2017-01-10    34.000000       8.00
2017-01-11    40.000000      12.00

<!-- Note about the linear interpolation result for a specific date. -->
**Notice that in above temperature on 2017-01-04 is 29 instead of 30 (in plain linear interpolate)**

<!-- Note that pandas supports many other interpolation methods beyond linear and time-based. -->
**There are many other methods for interpolation such as quadratic, piecewise_polynomial, cubic etc. 
Just google "dataframe interpolate" to see complete documentation**

<!-- Section header for dropna examples. -->
### <font color="blue">dropna</font>

In [11]:
# Drop any rows containing missing values and display the resulting DataFrame.
new_df = df.dropna()
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [12]:
# Drop only the rows where all values are missing and display the result.
new_df = df.dropna(how='all')
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [13]:
# Drop rows that do not have at least one non-missing value and display the result.
new_df = df.dropna(thresh=1)
new_df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

<!-- Section header for inserting missing dates into the index. -->
### <font color="blue">Inserting Missing Dates</font>

In [14]:
# Create a complete daily date range and reindex the DataFrame to include missing dates.
dt = pd.date_range("01-01-2017","01-11-2017")
idx = pd.DatetimeIndex(dt)
df.reindex(idx)

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny